# .config/cucumber.yml
##YAML Template
---
<% now = Time.now.to_i %>
<% default_args = " --color -r features -f pretty --expand --strict --tags ~@disabled --tags ~@orphaned" %>
<% common_libs = " -r features/step_definitions/ -r features/support/ "%>


default: <%= default_args %>
debug: CUCUSHIFT_LOG_LEVEL=debug CUCUSHIFT_DEBUG=true <%= default_args %>
devel: CUCUSHIFT_LOG_LEVEL=debug CUCUSHIFT_DEBUG=true CUCUSHIFT_DEVEL=true --expand --strict --color -r features -f pretty
#
# vim: set tabstop=2:shiftwidth=2:expandtab:
